/**
 * Book Name	- 	Apex Design Pattern
 * Chapter 2	-	Factory Method Pattern 
 * Descripton	-	"AdminPremiumSupport" changed to "AdminPremiumSupportImpl"
 * */
public class AdminPremiumSupportImpl implements IAdminSupport{
	
	/**
	*	return SLA in hours
	*/	
	public Integer getSLA()
	{
		return 12;
	}
	
	/**
	*	Total allowed support tickets allowed every month
	*/
	public Integer allowedTickets()
	{ 
		return 50;
	}
}