/**
 * Book Name	- 	Apex Design Pattern
 * Chapter 2	-	Factory Method Pattern 
 * Descripton	-	"AdminBasicSupport" changed to "AdminBasicSupportImpl"
 * */
public class AdminBasicSupportImpl implements IAdminSupport{
	
	/**
	*	return SLA in hours
	*/	
	public Integer getSLA()
	{
		return 40;
	}
	
	/**
	*	Total allowed support tickets allowed every month
	*/
	public Integer allowedTickets()
	{
		// As this is basic support so unlimited tickets
		return 9999;
	}
}